# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-10"

[[extensions]]
name = "why-buy-from-us-checkout"
handle = "why-buy-from-us-checkout"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
 [[extensions.settings.fields]]
 key = "container_heading"
 type = "single_line_text_field"
 name = "Container Heading"
 description = "Enter a heading for the container"
 [[extensions.settings.fields]]
 key = "section_one_title"
 type = "single_line_text_field"
 name = "Section one heading"
 description = "Enter a title for this section"
 [[extensions.settings.fields]]
 key = "section_one_description"
 type = "single_line_text_field"
 name = "Section one description"
 description = "Enter a description for this section"
 [[extensions.settings.fields]]
 key = "section_one_image"
 type = "single_line_text_field"
 name = "Section one image"
 description = "Image url for this section"
 [[extensions.settings.fields]]
 key = "section_two_title"
 type = "single_line_text_field"
 name = "Section two heading"
 description = "Enter a title for this section"
 [[extensions.settings.fields]]
 key = "section_two_description"
 type = "single_line_text_field"
 name = "Section two description"
 description = "Enter a description for this section"
 [[extensions.settings.fields]]
 key = "section_two_image"
 type = "single_line_text_field"
 name = "Section two image"
 description = "Image url for this section"
 [[extensions.settings.fields]]
 key = "section_three_title"
 type = "single_line_text_field"
 name = "Section three heading"
 description = "Enter a title for this section"
 [[extensions.settings.fields]]
 key = "section_three_description"
 type = "single_line_text_field"
 name = "Section three description"
 description = "Enter a description for this section"
 [[extensions.settings.fields]]
 key = "section_three_image"
 type = "single_line_text_field"
 name = "Section three image"
 description = "Image url for this section"