# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-04"

[[extensions]]
name = "checkout-ui-gwp-coupon"
handle = "checkout-ui-gwp-coupon"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.js"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"
 [[extensions.settings.fields]]
 key = "coupon_four_no_tier_gwp"
 type = "single_line_text_field"
 name = "Coupon to receive Single GWP - No Tier"
 description = "Coupon to receive GWPs"
 [[extensions.settings.fields]]
 key = "no_tier_gwp_variant_id"
 type = "single_line_text_field"
 name = "Variant Id of Single GWP - No Tier"
 description = "Variant Id of Single GWP - No Tier" 
 [[extensions.settings.fields]]
 key = "no_tier_gwp_quantity"
 type = "single_line_text_field"
 name = "Quantity for GWP - No Tier"
 description = "Quantity for GWP - No Tier" 
# [[extensions.settings.fields]]
# key = "require_subscription_purchase"
# type = "single_line_text_field"
# name = "Require Subsription For GWP"
# description = "Enter 'Yes' or 'No' (Case Sensitive)" 
